Step4
dreamisi/Moviebase pull request #3
Opened 2022-12-30 17:14 UTC by dreamisi

2023-01-15 09:21 UTC, georgyR requested changes
Также структура папок у тебя немного сломалась. Принято использовать applicationId (com.dreamisi.moviebase) в качестве корневой директории для кода приложения. Поэтому  для начала давай так разложим файлы в проекте
- com.dreamisi.moviebase - оставляем как есть
    - data
        - model
        - source

2023-01-15 09:21 UTC, georgyR commented on app/src/main/res/layout/view_holder_movie.xml
> +<androidx.constraintlayout.widget.ConstraintLayout
Есть несколько багов в верстке:
- В списке слишком большой отступ в центре между элементами RecyclerView
- В фигма карточка карточки фильмов имеют светлую обводку, у тебя она только частично есть с нескольких сторон

2023-01-15 09:21 UTC, georgyR commented on app/src/main/res/layout/view_holder_movie.xml
> +<androidx.constraintlayout.widget.ConstraintLayout
- В горизонтальной ориентации список выглядит странно. Как я понимаю этого в дизайне нет, но надо самому придумать ок-норм вариант. Предгалаю тянуть ячейку по горизонтали, что она занимала все доступное место. Картинку ограничиваем по высоте, при этом делаем android:scaleType="centerCrop" чтобы картинка адекватно вписалась в доступную область 

![Screenshot_20230115_170813](https://user-images.githubusercontent.com/29551897/212532462-6068a1f8-316b-47cf-9dc0-60df2b4ce18d.png)

2023-01-15 09:21 UTC, georgyR commented on app/src/main/res/layout/view_holder_movie.xml
> +<androidx.constraintlayout.widget.ConstraintLayout
- Увеличил размер экрана в настройках устройство и верстка поехала. Все из-за того что у тебя размер карточки завязан на размер картинки, так делать нельзя т.к. верстка д
олжна быть адаптивной под любой размер экрана. Лучше всегда указывать явный размер или match_parent для картинок, иначе будут такие баги
![Screenshot_20230115_170958](https://user-images.githubusercontent.com/29551897/212532618-289b09d2-8066-4066-9033-c51f9abc4e98.png)

2023-01-16 19:03 UTC, dreamisi commented on app/src/main/java/com/dreamisi/moviebase/MoviesListAdapter.kt
> +            duration.text = movie.duration + " MIN"
То есть любой текст стоит выкидывать в ресурсы?
Просто в данном случае я подумал, что это лишнее будет, сэтить айдишник, по нему вызывать текст.
Когда-то оправдано использование хардкода или это прям моветон?

2023-01-17 18:43 UTC, dreamisi commented on app/src/main/java/com/dreamisi/moviebase/FragmentMoviesDetails.kt
> +    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
Не понял что тут слиплось, я прогонял через автоформатирование код (ctrl+alt+L), у меня ничего не меняется, видимо надо настроить

2023-01-17 19:29 UTC, dreamisi commented on app/src/main/java/domain/ActorsDataSource.kt
> +package domain
Это я сделал как в воркшопе урока академии было:)

2023-01-17 19:32 UTC, dreamisi commented on app/src/main/res/layout/fragment_movies_list.xml
> +            />
Сделал автоформатирование, посмотрим что оно там изменило.
Пишу просто для инфы на будущее, чтобы не забыть

2023-01-18 03:23 UTC, georgyR commented on app/src/main/java/com/dreamisi/moviebase/FragmentMoviesDetails.kt
> +    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
Надо файл целиком смотреть. Не хватает пустых строк перед и после `private var recycler: RecyclerView? = null`
https://github.com/dreamisi/Moviebase/blob/7e23406578ea829ce799531f81233c2d35b82321/app/src/main/java/com/dreamisi/moviebase/FragmentMoviesDetails.kt#L11-L30

2023-01-18 03:23 UTC, georgyR commented on app/src/main/java/com/dreamisi/moviebase/FragmentMoviesDetails.kt
> +    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
Можем потом настроить с тобой конфиг на созвоне

2023-01-18 03:24 UTC, georgyR commented on app/src/main/java/com/dreamisi/moviebase/FragmentMoviesDetails.kt
> +        recycler?.layoutManager = LinearLayoutManager(requireContext(),HORIZONTAL,false)
Да, нет пробелов, форматирование кода должно фиксить это. Мб мы настроили форматирование перед коммитом на одном компе, а ты писал код на другом?

2023-01-18 03:27 UTC, georgyR commented on app/src/main/java/com/dreamisi/moviebase/MoviesListAdapter.kt
> +            duration.text = movie.duration + " MIN"
Для текстовых ресурсов никогда не оправдано хардкодить (в контексте реального проекта). Если это какой-то твой демо проект для каких-то экспериментов и тестов, то можно не заморачиваться. В данном случае мы стараемся писать приложение как настоящее, поэтому следуем все лучшим практикам

2023-01-18 03:31 UTC, georgyR commented on app/src/main/java/com/dreamisi/moviebase/MoviesListAdapter.kt
> +            duration.text = movie.duration + " MIN"
Еще не забудь, что есть строковые ресурсы с параметром, тебе как раз надо их использовать https://developer.android.com/guide/topics/resources/string-resource

2023-01-18 03:32 UTC, georgyR commented on app/src/main/java/domain/ActorsDataSource.kt
> +package domain
Ну че то хз) Даже по неймингу не несостыковочка

2023-01-18 17:25 UTC, dreamisi commented on app/src/main/java/com/dreamisi/moviebase/FragmentMoviesDetails.kt
> +        recycler?.layoutManager = LinearLayoutManager(requireContext(),HORIZONTAL,false)
Думал об этом. Вполне возможно. На следующем созвоне предлагаю эту тему разобрать кратко.

2023-01-21 19:06 UTC, dreamisi commented on app/src/main/res/layout/view_holder_movie.xml
> +<androidx.constraintlayout.widget.ConstraintLayout
"В списке слишком большой отступ в центре между элементами RecyclerView"
Вот этого не понял, вроде все ок 11dp должен быть по фигме 
![image](https://user-images.githubusercontent.com/73432381/213883046-395f6c61-f6a6-45c2-a2bd-ab89ca945312.png)

2023-01-28 08:14 UTC, georgyR requested changes
Давай еще уйдет от фиксированной ширины карточек путем перехода на CardView (как я тебе уже писал)

2023-01-28 08:14 UTC, georgyR commented on app/src/main/java/com/dreamisi/moviebase/MoviesListAdapter.kt
> +                val start_res = if (start_index <= movie.rating) {
Переменный в kotlin именуем в camelCase

2023-01-28 16:26 UTC, dreamisi commented on app/src/main/java/com/dreamisi/moviebase/MoviesListAdapter.kt
> +                val start_res = if (start_index <= movie.rating) {
а это я у тебя списал)))

2023-02-05 14:26 UTC, georgyR approved these changes

2023-02-05 14:26 UTC, georgyR commented on app/src/main/res/layout/view_holder_movie.xml
> +    android:layout_marginBottom="6dp"
можно заменить на один атрибут android:layout_margin="6dp"

2023-02-05 14:26 UTC, georgyR commented on app/src/main/res/layout/fragment_movies_list.xml
> +            android:layout_marginEnd="6dp"
start и end можно заменить на один android:layout_marginHorizontal="6dp"

2023-02-06 11:03 UTC, merged