Step5
dreamisi/Moviebase pull request #4
Opened 2023-03-30 14:53 UTC by dreamisi

2023-04-08 07:21 UTC, georgyR requested changes

2023-04-08 07:21 UTC, georgyR commented on app/src/main/java/com/dreamisi/moviebase/ActorsListAdapter.kt
> +        private val TAG = "ActorViewHolder"
Почему вдруг стиль нейминга поля? Вообще по сути стиль для такого типа поля правильный, только ты его не правильно задал. Поразбирайся в разнице между `val` и `const val`

2023-04-08 07:21 UTC, georgyR commented on app/src/main/java/com/dreamisi/moviebase/ActorsListAdapter.kt
> +    private val TAG = "ActorAdapter"
Тут че то отбившийся от стаи `val`) Плюс тоже же самое про `val` и `const val`

2023-04-08 07:21 UTC, georgyR commented on app/src/main/java/com/dreamisi/moviebase/MainActivity.kt
> +            .commit()
давай цепочку вызовов сделаем столбиком как было, так же красивей и понятней))

2023-04-08 07:21 UTC, georgyR commented on app/src/main/java/com/dreamisi/moviebase/MainActivity.kt
> +    private val jsonMovieRepository = JsonMovieRepository(this)
А почему решил хранить в activity это поле? Я думаю есть место получше среди базовых компонентов приложения

2023-04-08 07:21 UTC, georgyR commented on app/src/main/java/com/dreamisi/moviebase/MoviesDetailsFragment.kt
> +        val movieID = arguments?.getSerializable(MOVIE_ID) as Int? ?: return
Мы с тобой обсуждали. Тут лучше getInt писать.
Плюс лучше не ?: return делать, я бросать исключение. Пусть лучше крашится, чем ничего не происходит. В котлин есть обертка над `throw IllegalStateException` - метод `error()`. Текст ошибки сам придумаешь) достаточно описать почему ошибка произошла

2023-04-08 07:26 UTC, georgyR commented on app/src/main/java/com/dreamisi/moviebase/MainActivity.kt
> +    private val jsonMovieRepository = JsonMovieRepository(this)
Минус активити в том, что activity может пересоздаваться во время работы приложения. Это происходит при (копипаст из документации):
These include, but are not limited to:
- App display size
- Screen orientation
- Font size and weight
- Locale
- Dark mode versus light mode
- Keyboard availability
Поэтому activity не лучшее место для хранения общих вещей, которые нужны для работы всего приложения

2023-04-15 11:34 UTC, georgyR requested changes
Также хотелось обратить внимание на:
- У тебя у скопированных файлов неправильный пакеты (скрин прикрепил)
- Раз у тебя уже начал проект разрастаться, то давай файлы связанные определенным экраном складывать в одну папку. Допустим:
```
- movie_list
    - MoviesDetailsFragment
    - MoviesListAdapter
- movie_details
     - ...
```
<img width="1122" alt="Screenshot 2023-04-15 at 16 30 12" src="https://user-images.githubusercontent.com/29551897/232213856-e174e923-3c30-4278-996f-135b896964c6.png">

2023-04-15 11:34 UTC, georgyR commented on app/src/main/java/com/dreamisi/moviebase/MoviesListFragment.kt
> +
Как вариант, почему у тебя не всегда отображается контент на экране, это то, что ты сначала создаешь adapter, устанавливаешь его, а потом сетишь данные в adapter через `bindMovies`. При этом bindMovies просто добавляет данные в переменную внутри adapter и все.

Возможно в каких-то случаях получение данные происходит так быстро, что успеваем засетиться данные в adapter до начала инициализации RecyclerView. А в каких-то случаях RecyclerView инициализируется с пустым список фильмов

2023-04-15 11:34 UTC, georgyR commented on app/src/main/java/com/dreamisi/moviebase/MoviesListFragment.kt
> +
После bindMovies тебе надо явно сообщить RecyclerView, что данные обновились 😉

2023-04-15 11:34 UTC, georgyR commented on app/src/main/java/com/dreamisi/moviebase/MoviesListFragment.kt
> +    private val TAG = "MLF"
нигде не используется, можно удалить

2023-04-15 11:34 UTC, georgyR commented on app/src/main/res/layout/view_holder_movie.xml
> +            android:id="@+id/pg_text"
а что за `pg`?

2023-04-15 11:34 UTC, georgyR commented on app/src/main/java/com/dreamisi/moviebase/MoviesDetailsFragment.kt
> +
зачем пустые строки?

2023-04-15 11:34 UTC, georgyR commented on app/src/main/java/com/dreamisi/moviebase/MoviesDetailsFragment.kt
> +
Зачем пустые строки?

2023-04-15 11:34 UTC, georgyR commented on app/src/main/java/com/dreamisi/moviebase/MoviesDetailsFragment.kt
> +        }
А зачем тут apply для вызова всего одной функции?

2023-04-15 11:34 UTC, georgyR commented on app/src/main/java/com/dreamisi/moviebase/MoviesDetailsFragment.kt
> +    private val TAG = "MovieDetails"
А почему вдруг поле оказалось в низу файла, хотя все другие val/var вверху? А почему не camelCase?

2023-04-17 19:16 UTC, dreamisi commented on app/src/main/java/com/dreamisi/moviebase/data/MovieRepository.kt
> +internal class JsonMovieRepository(private val context: Context) : MovieRepository {
Этот код был дарован академией, не могу сказать почему так.
Но почитаю про то, когда уместно использовать internal

2023-04-17 19:50 UTC, dreamisi commented on app/src/main/res/layout/view_holder_movie.xml
> +            android:id="@+id/pg_text"
это векторный фон и текст, который меняется в зависимости от возрастного ограничения фильма 
![image](https://user-images.githubusercontent.com/73432381/232595139-9fe0d6fa-207d-48b5-a98b-171ac61af296.png)

2023-04-30 11:34 UTC, georgyR commented on app/src/main/java/com/dreamisi/moviebase/data/MovieRepository.kt
> +internal class JsonMovieRepository(private val context: Context) : MovieRepository {
Тут не уместно) Можешь убирать internal

2023-04-30 12:41 UTC, georgyR requested changes

2023-05-01 15:38 UTC, georgyR approved these changes

2023-05-01 15:38 UTC, merged