Step7: Networking
dreamisi/Moviebase pull request #6
Opened 2024-04-19 22:02 UTC by dreamisi

Added functional of getting data from themoviedb.org

2024-05-01 16:58 UTC, georgyR requested changes

2024-05-01 16:58 UTC, georgyR commented on app/src/main/java/com/dreamisi/moviebase/data/Repository.kt
> +        }
Тут в java стиле написано. В kotlin можно попроще)
```suggestion
        val cachedGenre = genreList ?: loadGenresFromDB()
        genreList = cachedGenre

        val cachedMovies = moviesList ?: loadMoviesFromDB(cachedGenre)
        moviesList = cachedMovies

        cachedMovies
```

2024-05-01 16:58 UTC, georgyR commented on app/src/main/java/com/dreamisi/moviebase/data/Repository.kt
> +        return parseGenre(data)
Опять же, в kotlin можно попроще делать такие приобразования без дополнительных переменных:
```suggestion
        return networkModule.theMovieDataBaseAPI
            .getGenreList()
            .let { parseGenre(it) }
```

2024-05-01 16:58 UTC, georgyR commented on app/src/main/java/com/dreamisi/moviebase/data/Repository.kt
> +    }
Есть такое понятие как "кодстайл". Это свод правил, по которому пишется код в проекте. Когда ты один, то его достаточно держать просто в голове и все).
Обычно в такой стиле есть принцип как располагаются поля и функции в классе. Вот у тебя уже сначала идут поля, потом функции. Еще классическое удобно правило - сначала публичные функции, а потом приватные. Это удобно тем, что сразу видно все публичные функции класса, именно они обычно интересуются пользователя класса.  Вот давай будем следовать этому правилу и поднимем эту фукнцию наверх

2024-05-01 16:58 UTC, georgyR commented on app/src/main/java/com/dreamisi/moviebase/data/services/TheMovieDataBaseAPI.kt
> +    "eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI5N2UyOWI4MTBhNGZlM2VlNDVjMTU5MDRkYWI1ZTA1MiIsInN1YiI6IjY1ZjViYzA5ZTAzOWYxMDE2NDAzNmJhZSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.JHAmBBmB33R3roiGUj2f_wgrMb
С ключами нужно быть аккуратней). Это твой личный ключ, он выдается именно лично тебе. Т.е. когда ты ходишь в api, то по нему сервер понимает, что это твое приложение.

А репозиторий у тебя публичный. Любой пользователь сети таким образом может найти твой ключ и использовать его в своих целях. Не очень хорошо. Поэтому его надо сложить в отдельный файл (просто kotlin файл с val). Добавить его в gitignore и не пушить в репозиторий.

2024-05-01 16:58 UTC, georgyR commented on app/src/main/java/com/dreamisi/moviebase/data/Repository.kt
> +            val genreFromDB = loadGenresFromDB()
DB - обычно имеется в виду локальная DB, в android она тоже есть https://developer.android.com/training/data-storage/sqlite. Поэтому я бы оставил просто loadGenres()

2024-05-01 16:58 UTC, georgyR commented on app/src/main/java/com/dreamisi/moviebase/data/services/TheMovieDataBaseAPI.kt
> +        @Header("Authorization") apiKey: String = "Bearer $API_KEY"
У тебя из запроса в запрос это повторяется. Наверное для каждого метода api нужен bearer. Можно на уровне ретрофита установить его
```kotlin
        .addInterceptor { chain ->
            val original = chain.request()
            val requestBuilder = original.newBuilder()
                .header("Authorization", "Bearer $API_KEY")
                .method(original.method, original.body)
            val request = requestBuilder.build()
            chain.proceed(request)
        }
```

2024-05-01 16:58 UTC, georgyR commented on app/src/main/java/com/dreamisi/moviebase/movieDetails/MoviesDetailsFragment.kt
> +            Glide.with(this).load("https://image.tmdb.org/t/p/w500/" + movieDetails.detailImageUrl).into(cover)
А у тебя эта ссылка повторяется и в app/src/main/java/com/dreamisi/moviebase/movieList/MoviesListAdapter.kt. И вообще эта логика не UI, а уровне, где у тебя данные грузятся и формируются. Давай будем формировать ссылку в repository

2024-05-01 16:58 UTC, georgyR commented on app/src/main/java/com/dreamisi/moviebase/data/NetworkModule.kt
> +object NetworkModule {
Ты сейчас получается используешь 2 способы с объектами, которые нужно создать 1 раз и использовать несколько раз:
- храним в application
- делаем класс object

Давай мб один способ выберем для одних задач)

2024-05-01 16:58 UTC, georgyR commented on app/src/main/java/com/dreamisi/moviebase/MovieBase.kt
> +class MovieBase : Application(), RepositoryProvider {
А в чем идея RepositoryProvider? ты же мог с таким же успехом создать функцию сразу в  этом классе без интерфейса

2024-05-01 16:58 UTC, georgyR commented on app/src/main/java/com/dreamisi/moviebase/MovieBase.kt
> +class MovieBase : Application(), RepositoryProvider {
```suggestion
class MovieBaseApplication : Application(), RepositoryProvider {
```

2024-05-01 17:00 UTC, georgyR commented on app/src/main/java/com/dreamisi/moviebase/data/Repository.kt
> +        return parseGenre(data)
Тут конечно мб вкусовщина, но я бы поправил по такому принципу и остальные функции в классе

2024-05-01 17:16 UTC, georgyR commented on app/src/main/java/com/dreamisi/moviebase/data/NetworkModule.kt
> +object NetworkModule {
Как по мне лучше в application. С такого подхода потом будет проще пересесть на полноценный DI.

2024-05-04 15:40 UTC, dreamisi commented on app/src/main/java/com/dreamisi/moviebase/MovieBase.kt
> +class MovieBase : Application(), RepositoryProvider {
Как я понял этот интерфейс обязует меня реализовать функционал передачи репозитория в целевые классы ( ViewModelFactory для обоих экранов)

2024-05-05 08:13 UTC, georgyR commented on app/src/main/java/com/dreamisi/moviebase/MovieBase.kt
> +class MovieBase : Application(), RepositoryProvider {
А разве так?  Во ViewModelFactory  ты приводишь applicatoin к MovieBase и у тебя есть доступ ко всем полям MovieBase. И получается без разницы какие там интерфейсы были реализованы.

Допустим убрав интерфейс, ничего не сломалось, код работает как и раньше.
<img width="1004" alt="Screenshot 2024-05-05 at 13 10 11" src="https://github.com/dreamisi/Moviebase/assets/29551897/f79ba1ef-aa45-43b6-9bab-a6b10e2cc476">

2024-05-05 09:04 UTC, georgyR requested changes

2024-05-05 09:04 UTC, georgyR commented on app/src/main/java/com/dreamisi/moviebase/data/Repository.kt
> +    }
Давай тут с неймигом разберемся. Сейчас у тебя как-то не очень понятно в чем разница между cachedGenre (тут как будто 1 genre), cachedGenreList и пр. Плюс поправил чутка код, на самом деле можно проще без emptyList
```suggestion
    suspend fun getMoviesList(): List<Movie> = withContext(Dispatchers.IO) {
        val localGenreList = cachedGenreList ?: loadGenres()
        cachedGenreList = localGenreList
        val localMoviesList = cachedMoviesList ?: loadMoviesFromDB(localGenreList)
        cachedMoviesList = localMoviesList
        localMoviesList
    }
```

2024-05-19 13:46 UTC, georgyR approved these changes

2024-05-19 13:46 UTC, merged